### PR TITLE
KTOR-6158 JS. Remove redundant `require` calls

### PR DESCRIPTION
**Pull request by turansky**
**Subsystem**
Client, JS

**Motivation**
https://youtrack.jetbrains.com/issue/KTOR-6158

**Solution**
Remove redundant `require` calls

### CODE REVIEW

**Review by e5l — APPROVED** [review]
please replace class with interface to avoid breaking changes

**Comment by turansky** [comment]
> please replace class with interface to avoid breaking changes

Done

**Comment by whyoleg** [comment]
Probably the same changes could be applied for wasmJs target

**Comment by Vampire** [comment]
Can we also get rid of the remaining two `require` calls? (for `ws` and `crypto`)
I guess the same problems will be hit with those if their code paths are hit?

**Comment by turansky** [comment]
> Can we also get rid of the remaining two require calls? (for `ws` and `crypto`)

2 additional separated PR-s (1 for `ws` and 1 for `crypto`) - preferable option

**Comment by turansky** [comment]
@osipxd Thank you for assistance :)

**Pull request merged**
