### PR TITLE
KTOR-1460 Switch to org.w3c.fetch

### PR DESCRIPTION
**Pull request by hfhbd**
2nd PR after [KTOR-2230](https://youtrack.jetbrains.com/issue/KTOR-2230)

**Subsystem**
Client, JS

**Motivation**
[KTOR-1460](https://youtrack.jetbrains.com/issue/KTOR-1460)
- browser: Reduce code size by using std lib provided fetch api/classes
- nodeJS: added minimal defined classes manually

**Solution**
Switch to org.w3c.fetch or use manually defined classes on nodeJS

### CODE REVIEW

**Comment by hfhbd** [comment]
As you can not test `nodeJsProductionRun` in unit tests, I used this test project: https://github.com/hfhbd/ktorTestNodeJS with `mavenLocal`

**Review by e5l — COMMENTED** [review]
LGTM, can be merged after CI run

**Review by e5l — APPROVED** [review]

**Comment by e5l** [comment]
Could you rebase if if it's actual or should we close?

**Comment by hfhbd** [comment]
Sorry for the late answer. I rebased it, but removing the classes will break abi.

**Pull request closed without merging**
