### PR TITLE
KTOR-3749 Add jte template support

### PR DESCRIPTION
**Pull request by Masterzach32**
**Subsystem**
Server plugin

**Motivation**
Adds support for the jte template engine, you can read more about it here: https://jte.gg/

https://youtrack.jetbrains.com/issue/KTOR-3749

**Solution**
This PR adds a plugin that transforms `JteContent` using a `.jte` or `.kte` template into content that can be served by Ktor.

For example:

```kotlin
fun Application.module(testing: Boolean = false) {
    install(Jte) {
        templateEngine = TemplateEngine.create(
            DirectoryCodeResolver(Path.of("src", "main", "kte")),
            ContentType.Html
        )
    }

    routing {
        get("/") {
            call.respondTemplate("hello.kte", "name" to "world")
        }
    }
}
```

`hello.kte`:
```html 
@param name: String
<p>Hello ${name}!</p>
```

### CODE REVIEW

**Comment by rsinukov** [comment]
Hi @Masterzach32,
In general, looks good. But can you please try out new plugins API? You can use as a reference other template plugins. They were rewritten last week.

**Comment by Masterzach32** [comment]
Yes, I'll port the changes to the new plguin API

**Comment by Masterzach32** [comment]
Fixed the style errors, removed the extra api specs and bumped Jte version to 2.0.0. This should be ready to merge!

**Review by rsinukov — APPROVED** [review]
LGTM

**Pull request merged**
