### PR TITLE
Added a JacksonSupport feature.

### PR DESCRIPTION
**Pull request by magnuschatt**
Added a module very similar to GsonSupport, which uses Jackson instead of GSON. I really don't like the fact that GSON breaks Kotlins null safety by inserting nulls into non-nullable fields, without throwing an exception!

### CODE REVIEW

**Comment by magnuschatt** [comment]
Oh wow! Didn't see the other Jackson pull request. You may reject this.

**Comment by magnuschatt** [comment]
Oh wow! Didn't notice the other Jackson pull request... You may do with this pull request as you like, as long some sort of Jackson support is merged :)

**Comment by orangy** [comment]
That one is really old and probably doesn't match current architecture. Thank you!

**Comment by dinomite** [comment]
I like it and it works with my cursory testing.

**Comment by orangy** [comment]
Will be obsoleted by #167, but we will still need Jackson integration, so I'm leaving it open for future reference.

**Comment by rocketraman** [comment]
Works for me out of the box as well, whereas GsonSupport did not.

**Comment by orangy** [comment]
Will merge another PR with current architecture. Thank you for your effort! I was too slow to merge it working on ContentNegotiation feature.

**Pull request closed without merging**
