### PR TITLE
KTOR-381 Non US-ASCII characters are prohibited

### PR DESCRIPTION
**Pull request by vladf2n**
**Subsystem**
ktor-http

**Motivation**
[KTOR-381 Non US-ASCII characters are prohibited](https://youtrack.jetbrains.com/issue/KTOR-381)
#1865  

**Solution**
Check if every character from a request/response is US-ASCII.

### CODE REVIEW

**Comment by cy6erGn0m** [comment]
As far as I remember some browsers produce requests having non-ascii characters in some headers. Don't remember where exactly, perhaps it about multipart file upload or something related... Let me check

**Comment by vladf2n** [comment]
Thank you for your response. Ok I'm waiting!

**Comment by cy6erGn0m** [comment]
Ok, looks like we call `parseHeaders` directly in the multipart parser. However, I am reading the RFCs to ensure that we don't miss anything as I am too scary to introduce such restrictions so easily :)

**Comment by cy6erGn0m** [comment]
The other reason for doubts is that other servers allow non-ASCII characters

**Comment by vladf2n** [comment]
Hmm... got it. So, how do you think I should proceed?

**Comment by cy6erGn0m** [comment]
I am not sure. Wait please a little bit more. We'll discuss it

**Comment by vladf2n** [comment]
Okay!

**Pull request closed without merging**
