### PR TITLE
OAuth2: Added option to pass params in URL

### LINKED ISSUE #1846: No ability to get Gitlab OAuth working in KTor with settings available
**Ktor Version and Engine Used (client or server and name)**
1.3.2

**Describe the bug**
I tried to get Gitlab working as an OAuth2 provider in KTor. After some tinkering I've ended up with something like this:
```kotlin
                OAuthServerSettings.OAuth2ServerSettings(
                    name = "gitlab",
                    authorizeUrl = "https://gitlab.com/oauth/authorize",
                    accessTokenUrl = "https://gitlab.com/oauth/token",
                    requestMethod = HttpMethod.Post,
                    clientId = ...,
                    defaultScopes = listOf("read_user", "profile", "api"),
                    clientSecret = ...
                )
```
The problem is that `requestMethod = Post` moves parameters a request into body, and GitLab expects them in URL. Thus it doesn't work.

**To Reproduce**
0. Register GitLab application and get clientId and secret. 
1. Create a OAuth2 provider with given settings
2. Try authorizing

**Expected behavior**
I would like to be able to specify, whether request parameters are in URL or in body, so not to break exising authenticators.

### PR DESCRIPTION
**Pull request by cab404**
This allows to use GitLab OAuth2 provider.
Fixes #1846 

**Subsystem**
:ktor-features:ktor-auth

**Motivation**
This allows to use GitLab OAuth2 provider.

**Solution**
Added option to pass token retrieval params in URL instead of body in POST requests.

### CODE REVIEW

**Comment by cab404** [comment]
Anyone's alive?

**Comment by cab404** [comment]
...guys?

**Comment by e5l** [comment]
Hi @cab404, thanks for the PR.
LGTM, but could you add the test for the new feature?

**Comment by cab404** [comment]
> LGTM, but could you add the test for the new feature?

Okay, gonna try that. It's kind of hard to make this project compile in NixOS :D

**Comment by e5l** [comment]
You can use `jvm` only tasks to keep things easy :)

**Comment by cab404** [comment]
> You can use `jvm` only tasks to keep things easy :)

Oh, thanks)

**Comment by cab404** [comment]
Ooof. @e5l that took some time. Could you please see, if that can be optimized more?

**Comment by e5l** [comment]
LGTM. Merged

**Pull request merged**
