### PR TITLE
Add the ability to defer MDC entry computation

### PR DESCRIPTION
**Pull request by CarrotCodes**
**Subsystem**
ktor-server-jvm

**Motivation**
As discussed in https://github.com/ktorio/ktor/issues/604, it's not currently possible to add MDC entries with values that contain response information.

Services like Datadog are set up to pull response codes out of predefined MDC entries, so it would be helpful to support this out of the box.

**Solution**
I've added a parameter to `MDCEntry` called `defer`, with a default value of `false` so as to keep existing behaviour the same.

Deferred MDC entries have the same lifecycle / management as regular entries, but their values are set to `null` to start with. After a request has been handled, but before the result is logged, we compute the value of any `MDCEntry` marked as being deferred.

I've also added a couple of tests to make sure existing behaviour, without `defer`, is maintained, and that the deferred entries survive context switches (using the existing tests as examples to follow).

This is my first PR - I'm more than happy to change this as desired, and for you to make changes, just let me know.

### CODE REVIEW

**Review by e5l — APPROVED** [review]
Hey @CarrotCodes, thanks for the PR! LGTM, could you rebase it on `main`?
We can merge it in `2.0.0`

**Comment by CarrotCodes** [comment]
> Hey @CarrotCodes, thanks for the PR! LGTM, could you rebase it on `main`? We can merge it in `2.0.0`

Thanks for taking a look @e5l - I've rebased and tweaked the tests a little to match the code style around them. I'm having trouble running the entire `jvmTest` suite but everything in `CallLoggingTest` is happy locally at least.

**Comment by CarrotCodes** [comment]
I rebased to fix the conflicts and I believe this PR might not be necessary any more after https://github.com/ktorio/ktor/pull/2716 - tests seem to show status codes being logged just fine 🤞 

Let me know if it's still needed and I'll reopen, otherwise going to close now to reduce the number of PRs you have to look at.

**Comment by e5l** [comment]
@CarrotCodes, thank you for the contribution!

**Pull request closed without merging**
