### PR TITLE
Gradle buildSrc config tidying

### PR DESCRIPTION
**Pull request by adam-enko**
**Subsystem**
Client/Server, related modules

**Motivation**
Describe what problem this PR solves and why it is important. Refer to a bug/ticket #.

**Solution**
Describe your solution.

### CODE REVIEW

**Comment by e5l** [comment]
Hey @adam-enko, could you please rebase the PR on the main branch?

**Comment by adam-enko** [comment]
@e5l done

**Comment by e5l** [comment]
Thanks @adam-enko, looks nice!

**Review by e5l — APPROVED** [review]

**Comment by e5l** [comment]
Will be merged in a moment, after 3.0.0-beta-2 built is finished

**Pull request merged**
