### PR TITLE
KTOR-2822 Change `HttpReceivePipeline` context to Unit

### PR DESCRIPTION
**Pull request by rsinukov**
Otherwise, it's impossible to modify response, since context has its own instance of response.

### CODE REVIEW

**Review by e5l — CHANGES_REQUESTED** [review]
please check compilation failures

**Review by e5l — CHANGES_REQUESTED** [review]
It looks like the JVM `numberTest` is failing without flaky here. Could you take a look?

**Comment by rsinukov** [comment]
@e5l thanks, fixed. I decreased the test timeout for debugging purposes and forgot to change it back.

**Review by e5l — APPROVED** [review]
Please check if we need to make documentation for that and make new ticket if we need

**Pull request merged**
