### PR TITLE
Update KtorSimpleLoggerJs.kt

### PR DESCRIPTION
**Pull request by aggarwalpulkit596**
**Subsystem**
Ktor-Utils

**Motivation**
Configuring JS Client for Browser platform.

In our organisation we are currently using a Kotlin multiplatform based SDK which relies on ktor for networking. However there is a slight inconvience with the browser platform being bombarded with trace logs. When we were exploring possible solutions for the same, we found this https://github.com/ktorio/ktor/pull/3783/files, which solves our problem partially by adding a env for configuring trace logs but this doesn't work for us as our platform is a pure client side facing application which runs in browser.

**Solution**
Adding a simple conditional for the KtorSimpleLogger in which we check for both Node and Browser platform.

### CODE REVIEW

**Review by RivuChk — APPROVED** [review]

**Review by e5l — APPROVED** [review]

**Comment by e5l** [comment]
Hey @aggarwalpulkit596, thanks for the PR. LGTM, merged

**Comment by Legion2** [comment]
Hi I'm trying to use ktor client in my wasm app and facing an issue related to this change:
```
process is not defined
ReferenceError: process is not defined
    at io.ktor.util.logging.getKtorLogLevel (webpack-internal:///./kotlin/composeApp.uninstantiated.mjs:4091:68)
    at <de.voize.core:web>.io.ktor.util.logging.getKtorLogLevel__externalAdapter (http://localhost:8080/composeApp.wasm:wasm-function[20569]:0x4596d6)
    at <de.voize.core:web>.io.ktor.util.logging.<no name provided>.<init> (http://localhost:8080/composeApp.wasm:wasm-function[20570]:0x459776)
    at <de.voize.core:web>.io.ktor.util.logging.KtorSimpleLogger (http://localhost:8080/composeApp.wasm:wasm-function[20568]:0x4596cc)
    at <de.voize.core:web>.io.ktor.client.plugins.<init properties HttpRequestLifecycle.kt> (http://localhost:8080/composeApp.wasm:wasm-function[22345]:0x47a83e)
    at <de.voize.core:web>.io.ktor.client.plugins.<get-HttpRequestLifecycle> (http://localhost:8080/composeApp.wasm:wasm-function[22314]:0x479dc1)
    at <de.voize.core:web>.io.ktor.client.HttpClient.<init> (http://localhost:8080/composeApp.wasm:wasm-function[21759]:0x46dee1)
    at <de.voize.core:web>.io.ktor.client.HttpClient.<init> (http://localhost:8080/composeApp.wasm:wasm-function[21765]:0x46e0df)
    at <de.voize.core:web>.io.ktor.client.HttpClient (http://localhost:8080/composeApp.wasm:wasm-function[21782]:0x46e4f1)
    at <de.voize.core:web>.App$lambda.invoke (http://localhost:8080/composeApp.wasm:wasm-function[69102]:0x8a0c95)
```
`private fun getKtorLogLevel(): String? = js("process.env.KTOR_LOG_LEVEL")`
In browser environment the `process` property is not defined which causes the ReferenceError.

**Comment by e5l** [comment]
Hey, as workaround you can try defining it manually in `index.html`, please check ktor-samples for the complete wasm sample

**Comment by Stexxe** [comment]
Also, the `runCatching` problem (the error shouldn't be thrown) has been fixed in Kotlin multiplatform of version **2.0.0-Beta5**.

**Pull request merged**
