### PR TITLE
KTOR-3783 Use global DslMarker

### PR DESCRIPTION
**Pull request by rsinukov**
Fixes https://youtrack.jetbrains.com/issue/KTOR-3333

### CODE REVIEW

**Review by e5l — APPROVED** [review]
Good job, lgtm

**Comment by hfhbd** [comment]
This only works, iff a 3rd party plugin also uses `KtorDSL`, doesn't it?

**Comment by e5l** [comment]
@hfhbd all receivers should be marked

**Comment by hfhbd** [comment]
Yeah sure. I like the solution, but only want to notice a 3rd party plugin author has to add the annotation. So this should be written in the docs.

**Comment by rsinukov** [comment]
@hfhbd Yes, it should be. 
@andreyaksenov, When you will work on docs for custom plugins, please consider adding that config classes should be annotated with `@KtorDsl`

**Pull request merged**
