### PR TITLE
Official Gradle Wrapper Validation GitHub Action

### PR DESCRIPTION
**Pull request by JLLeitschuh**
See: https://github.com/gradle/wrapper-validation-action

### CODE REVIEW

**Comment by cy6erGn0m** [comment]
Like it, thanks!

**Comment by cy6erGn0m** [comment]
```
Current runner version: '2.158.0'
Prepare workflow directory
Prepare all required actions
Download action repository 'actions/checkout@v2'
##[error](Line: 6, Col: 14):
##[error](Line: 17, Col: 14):
##[error](Line: 35, Col: 3): Unexpected value 'post'
##[error](Line: 6, Col: 14): Unrecognized named-value: 'github'. Located at position 1 within expression: github.repository
##[error](Line: 17, Col: 14): Unrecognized named-value: 'github'. Located at position 1 within expression: github.token
##[error](Line: 35, Col: 3): Unexpected value 'post'
##[error]Fail to load /home/runner/work/_actions/actions/checkout/v2/action.yml
```

**Comment by cy6erGn0m** [comment]
@e5l this was merged and reverted, sorry for some noise. Didn't expect it to not work. Looks like the work "official" does magic :)

**Comment by JLLeitschuh** [comment]
I'm encountering this in a very low number of repositories I'm contributing this to.
https://github.com/actions/checkout/issues/137

**Pull request merged**
