### PR TITLE
Add shortcut function to configure the json instance

### PR DESCRIPTION
**Pull request by bluefireoly**
**Subsystem**
ktor-features/ktor-serialization

**Motivation**
While with gson and jackson together with ktor you can do the following to configure the instances:
```kt
install(ContentNegotiation) {
    gson {
        // Configure Gson here
    }
}
```
... with kotlinx.serialization you have to do the following:
```kt
install(ContentNegotiation) {
    json(Json {
        // Configure kotlinx.serialization here
    })
}
```
... which most new users do not know.

**Solution**
With the new function I added, this is not the case anymore:
```kt
install(ContentNegotiation) {
    json {
        // Configure kotlinx.serialization here
    }
}
```

In my opinion, this is much more intuitive to use.

### CODE REVIEW

**Comment by hhariri** [comment]
Thanks for the PR. There are a few issues here, namely two: 

1. gson/jackson is referring to library names, whereas json is referring to a format. 
2. Kotlinx serialisation provides more than just JSON and this could be confusing if we were to use this function name. 

It does make sense to provide some defaults and remove boilerplate code. Do you have a suggestion for another name for this?

**Review by hhariri — CHANGES_REQUESTED** [review]
Thanks for the PR. There are a few issues here, namely two:

1. gson/jackson is referring to library names, whereas json is referring to a format.
2. Kotlinx serialisation provides more than just JSON and this could be confusing if we were to use this function name.

It does make sense to provide some defaults and remove boilerplate code. Do you have a suggestion for another name for this?

**Comment by bluefireoly** [comment]
I was not the one who named this function json, Ktor already has a function called `json`, which just did not provide a lamda for configuring the instance.
Also, previously the `json` function for configuring kotlinx.serialization was called `serialization`, I would not change this again.

However if you really want to change the name, then I suggest `kotlinxSerialization` - that would follow the scheme of the other function names.

**Comment by bluefireoly** [comment]
Here is a [link to the function](https://github.com/ktorio/ktor/blob/b2feeccbc5b9d4202673cf97ca6ae6f25d0d10b6/ktor-features/ktor-serialization/jvm/src/io/ktor/serialization/JsonSupport.kt#L88) which already exists in Ktor. That is why I named my additional function `json` aswell.

Additionally, I think that the name `json` is indeed a good name, because users should be encouraged to use kotlinx.serialization:
- it is multiplatform
- by jetbrains
- an official kotlinx library

**Comment by hhariri** [comment]
@bluefireoly Yeah, it's not ideal we have that there either. But the issue is Serialization isn't limited to json. And yet this is somewhat implying that. Does that make sense?

**Comment by bluefireoly** [comment]
I understand your point, but what this function does is creating a `Json` instance of kotlinx.serialization - and that instance is limited to json.

**Comment by hhariri** [comment]
Very much appreciate the contribution, but as it stands we need to rethink this. I've created a design ticket to further discuss how we can do this. https://youtrack.jetbrains.com/issue/KT-46046

**Comment by bluefireoly** [comment]
I really support the design ticket you created there and I am aswell of the opinion that this must be rethought, BUT would it maybe be possible to merge this PR anyways, just to make the current API more consistent UNTIL that major serialization API change is coming?

**Comment by hhariri** [comment]
The issue with merging this is that any new API we provide we'll need to then move to a deprecation cycle...

**Comment by bluefireoly** [comment]
So you think the lifespan of this feature would be too short?

**Comment by hhariri** [comment]
Yes. The design ticket should be approved soon, and we could try and implement the functionality rather soon.

**Pull request closed without merging**
