### PR TITLE
KTOR-2626 Remove internal require function

### PR DESCRIPTION
**Pull request by hfhbd**
**Subsystem**
Server, IO Internal

**Motivation**
https://youtrack.jetbrains.com/issue/KTOR-2626

**Solution**
Switch to stdlib require function

### CODE REVIEW

**Review by rsinukov — CHANGES_REQUESTED** [review]
Please commit `apiDump` result

**Comment by hfhbd** [comment]
@rsinukov Okay, but removing a internal functions won't change the api, BUT there are a lot of missing apiDumps from other changes..

**Comment by rsinukov** [comment]
Since this function was annotated with `@PublishedApi` it was effectively public, so it was part of binary API

**Comment by hfhbd** [comment]
@rsinukov Yes, but other`@PublishedApi` annotated functions are also not printed in the .api file as well (https://github.com/ktorio/ktor/blob/9c902b3c001f40bafe744d8d27573487d54c670c/ktor-features/ktor-auth/jvm/src/io/ktor/auth/SessionAuth.kt#L30). Don't know if it is a wrong configuration or a bug in the validator itself.

**Comment by rsinukov** [comment]
@hfhbd hm, thanks for pointing out, they should be in the dump. 
In the dump that you published there are things that were deleted in 2.0.0. Can you do apiDump with clean build, or even deleted `.gradle` folder? Somtimes it caches too much and you have dumps from different branches.

**Comment by hfhbd** [comment]
@rsinukov Done :D

**Review by rsinukov — APPROVED** [review]

**Comment by hfhbd** [comment]
So, for some reasons `apiDump` does not remove the included lines https://github.com/ktorio/ktor/blob/ec9bd2fada9b149f69b758bd1eb474e7ef3a6e01/ktor-io/api/ktor-io.api#L1753

a) I remove the files manually.
b) Fix the binary validator settings, if possible. I did remove all custom settings regarding the plugin, update it to `0.5.0`, but it still did not delete the lines.

**Comment by rsinukov** [comment]
Please rebase and I will merge it. I'll fix apiDump later myself.

**Comment by hfhbd** [comment]
@rsinukov rebased

**Pull request merged**
