### PR TITLE
Add JacksonSerializer #477 

### PR DESCRIPTION
**Pull request by danielmischler**

### CODE REVIEW

**Comment by e5l** [comment]
Hi, @danielmischler. Thanks for the PR :)

Could you add some tests on complex nested(`List<User<String>>`) generic types?

**Comment by danielmischler** [comment]
Hi @e5l

I'm not a git/github pro so I don't really know what I can/have to do to resolve the conflicts.
Please let me know.

**Comment by e5l** [comment]
Don't worry about conflicts. I'll rebase it on done. 
Btw did you test some complex generic cases? It looks like here we use the wrong type from the `TypeInfo` instance.

**Comment by e5l** [comment]
Unable to merge here, so merged through a terminal.
Awesome job, thanks.

**Pull request closed without merging**
