### PR TITLE
KTOR-2678 Add support for watchosX64 target

### PR DESCRIPTION
**Pull request by Thomas-Vos**
Fix https://youtrack.jetbrains.com/issue/KTOR-2678

Tested using `./gradlew watchosX64Test` and the build was successful.

### CODE REVIEW

**Review by e5l — APPROVED** [review]

**Comment by e5l** [comment]
Thanks for the PR, lgtm, merged.

**Comment by PaulWoitaschek** [comment]
@e5l It seems the artifacts were not published.

**Comment by Thomas-Vos** [comment]
I'm not sure why watchosX64 was not published. I used `publishToMavenLocal` to test this and they were published locally.

**Comment by e5l** [comment]
It's because of the build configuration. Checked and fixed the configs, will try to republish soon

**Comment by RdeWilde** [comment]
@e5l did republishing work?

**Comment by PaulWoitaschek** [comment]
@RdeWilde it was decided to postpone it to 1.6.2 which should be released approx end of July.

**Pull request merged**
