### PR TITLE
Add fast compilation and jvmTest check for PRs

### PR DESCRIPTION
**Pull request by e5l**
Add fast check for compilation and jvmTests

### CODE REVIEW

**Comment by Mr3zee** [comment]
@e5l I'm not an expert in GH Actions, but maybe the error will go away when using this https://github.com/gradle/gradle-build-action ?

**Comment by e5l** [comment]
I'm not sure, cause it's already started gradle but can't find dependencies:
```
e: file:///home/runner/work/ktor/ktor/ktor-io/common/src/io/ktor/utils/io/temporary.kt:4:50 Unresolved reference: coroutines
```

**Comment by hfhbd** [comment]
It is the correct action, but using the argument syntax is deprecated. Anyway, this is unrelated to the actual compiling failure, which was caused by a wrong commit: I used the main branch and it did work: https://github.com/hfhbd/ktor/pull/91
BTW you can also remove the wrapper validation file and just enable: `validate-wrappers: true`. Alternatively, I can create the PR.

**Comment by e5l** [comment]
@hfhbd, thanks. It helped.

@Mr3zee, fixed. Please check.

**Review by Mr3zee — DISMISSED** [review]

**Comment by hfhbd** [comment]
But keep in mind, the build doesn't fail if a jvm test failed.

**Comment by e5l** [comment]
Yep, let me check if we can bring test results to the UI

**Pull request closed without merging**
