### PR TITLE
KTOR-4515 set realm before it's used to create credential

### PR DESCRIPTION
**Pull request by sproctor**
**Subsystem**
ktor-client-auth 

**Motivation**
https://youtrack.jetbrains.com/issue/KTOR-4514/DigestAuthProvider-realm-sent-from-the-server-doesnt-participate-in-the-computation-of-response

Connecting to Axis cameras fails without this fix

**Solution**
Prior to this change, the realm used in the `credential` was always the class property. If the realm is unknown, it should be read from the headers. This was happening, but after the `credential` was created.

This change uses the constructed `realm` in the `credential` instead of the class property.

### CODE REVIEW

**Comment by rsinukov** [comment]
And I see that CodeStyle task fails. Please run `./gradlew formatKotlin` to fix it.

**Comment by sproctor** [comment]
I'm not sure how to write that test. there's an example at the youtrack report, but I don't think hitting an external server is ok. A bit of direction would be nice and I'll try to write the test next week.

**Comment by sproctor** [comment]
Sorry about the noise in `HttpStatusCode`. I have no idea where that came from, I didn't edit that file.

The bug is that the token is incorrect when the server specifies a realm, but the client doesn't provide one. I've added a weak test for this. It just asserts that the response token matches what was produced locally for me. This doesn't test the path where `qop` is set because that is much more complicated.

**Comment by ninja-** [comment]
I just checked it also fixed Dahua support. thanks :)

**Pull request merged**
