### PR TITLE
CIO engine no longer sends port in "Host" header

### LINKED ISSUE #1294: KTOR client CIO engine sends bad "Host" http header (includes port number)
**Ktor Version and Engine Used (client or server and name)**
1.2.2, client, CIO

**Describe the bug**
ktor client with CIO engine sends port number in host header. `Host: test.com:80`

This has caused 2 problems so far

1) the external service had routing rules based on host. `test.com` routed correctly, `test.com:443` did not route and sent 404s. All other major http clients (browser, curl, python, okhttp, etc) do not append the port to the host header (and worked correctly).

2) aws s3 pre-signed urls. the host in the header did not match the host that was signed in the presigned url, caused aws signatures to not match and request to be refused.

**To Reproduce**

```kotlin
val client = HttpClient(CIO)
client.get("http://test.com")
```
**Expected:**
```
GET  HTTP/1.1
Host: test.com
....
```
**Actual:**
```
GET  HTTP/1.1
Host: test.com:80
....
```

**To Fix**
change this line
https://github.com/ktorio/ktor/blob/0e4a6f24e40c756a35913d466036f0dc59519cc1/ktor-client/ktor-client-cio/jvm/src/io/ktor/client/engine/cio/utils.kt#L31

to
```kt
        builder.headerLine("Host", url.host)
```

### PR DESCRIPTION
**Pull request by Evyy**
Fixes #1294

see #1294 for details

### CODE REVIEW

**Comment by Evyy** [comment]
I looked through the tests before I submitted to see if this change would cause anything to fail. I did not see anything. 

I would be happy to fix any broken tests, but I can't access the test failure results. Is there a way that I can access them?

**Comment by Evyy** [comment]
Oh nevermind, I figured it out. sorry. looking at test results now.

**Comment by Evyy** [comment]
fixed the two tests that were broken. 

I have no idea why this one would be failing..

https://github.com/ktorio/ktor/blob/2296583e7663b85c80d3a38dc5fe1bbfc15895d2/ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/ContentTest.kt#L86-L95


`ContentTest.testTextContent[Apache]`
```
java.util.concurrent.CancellationException: Fail to execute request
	at    (Coroutine boundary. ( )
	at kotlinx.coroutines.io.ByteBufferChannel.readRemainingSuspend(ByteBufferChannel.kt:2201)
	at io.ktor.client.features.HttpPlainText$Feature$install$2.invokeSuspend(HttpPlainText.kt:140)
Caused by: java.util.concurrent.CancellationException: Fail to execute request
	at kotlinx.coroutines.ExceptionsKt.CancellationException(Exceptions.kt:33)
	at io.ktor.client.engine.apache.ApacheResponseConsumer.failed(ApacheResponseConsumer.kt:118)
	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.executionFailed(DefaultClientExchangeHandlerImpl.java:99)
	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.failed(AbstractClientExchangeHandler.java:426)
	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.timeout(HttpAsyncRequestExecutor.java:381)
	at org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:92)
	at org.apache.http.impl.nio.client.InternalIODispatch.onTimeout(InternalIODispatch.java:39)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.timeout(AbstractIODispatch.java:175)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.sessionTimedOut(BaseIOReactor.java:263)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.timeoutCheck(AbstractIOReactor.java:492)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.validate(BaseIOReactor.java:213)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:280)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.net.SocketTimeoutException: 10,000 milliseconds timeout on connection http-outgoing-25 [ACTIVE]
	... 11 more
```

Flakey test maybe? not sure.

**Comment by Bluexin** [comment]
See [ietf](https://tools.ietf.org/html/rfc7230#section-5.4) on the Host header :
> Host = uri-host [ ":" port ] ;

Port is optional, but part of the spec.

It follows the http URI scheme, defined in [section 2.7.1](https://tools.ietf.org/html/rfc7230#section-2.7.1) :
> If the port subcomponent is empty or not given, TCP port 80 (the reserved port for WWW services) is the default.

**Comment by e5l** [comment]
Hi @Evyy, thanks for the PR. Merged in `e5l/develop`.

**Pull request merged**
