### PR TITLE
KTOR-2435 Fix MDC context in client response body logging

### PR DESCRIPTION
**Pull request by rsinukov**
https://youtrack.jetbrains.com/issue/KTOR-2435

### CODE REVIEW

**Comment by e5l** [comment]
Could you please check CI first?

**Comment by e5l** [comment]
please also consider a test scenario, when user is receiving with logging on already finishing call

**Comment by rsinukov** [comment]
@e5l thanks, I updated the implementation to use the same scope as before

**Review by e5l — APPROVED** [review]
LGTM!

**Pull request merged**
