### PR TITLE
KTOR-7255 Fix descriptor leak when closing socket and selector

### PR DESCRIPTION
**Pull request by Thomas-Vos**
[KTOR-7255](https://youtrack.jetbrains.com/issue/KTOR-7255) Closing socket and selector leaks descriptor on native

### CODE REVIEW

**Comment by Thomas-Vos** [comment]
Do not merge this before #4151

**Comment by Thomas-Vos** [comment]
I had to add the test in nix instead of posix because `fcntl` is unavailable in windows. So unfortunately there is no close test for windows.

**Comment by e5l** [comment]
Hey @Thomas-Vos, thank you for the great job! Could you please rebase on the main? I've merged windows PR and there are some conflicts

**Comment by Thomas-Vos** [comment]
@e5l rebased

**Review by e5l — APPROVED** [review]

**Pull request merged**
