### PR TITLE
KTOR-6173 Support ktor-client-curl for linuxArm64

### PR DESCRIPTION
**Pull request by selcarpa**

### CODE REVIEW

**Comment by e5l** [comment]
Hey @selcarpa, thanks for the PR. I will setup Linux arm64 test configuration to check the PR shortly :)

**Comment by selcarpa** [comment]
> Hey @selcarpa, thanks for the PR. I will setup Linux arm64 test configuration to check the PR shortly :)

OK, thanks for your help. Since I don't know much about the kotlin native library, here is a static link based on the mingw64 target. If there's a problem I'll try to fix it

**Comment by e5l** [comment]
Hey @selcarpa, unfortunately, we can't build and run ktor tests on the Arm64 host due to: https://youtrack.jetbrains.com/issue/KT-36871

We will check the build only

**Review by e5l — APPROVED** [review]
CI is good. LGTM, merged

**Comment by selcarpa** [comment]
Hello, this commit can actually only generate klib through compilation, and has not been successfully used on armlinux devices. The reason is that I cannot correctly use the locally built klib package. Can you help me try whether this runs correctly on arm devices.

**Comment by selcarpa** [comment]
Anyway, I tested this commit again, there are still some problems, I am trying to re-debug the static link.
Please do not carry this content into the next release@e5l

**Comment by e5l** [comment]
Hey, thank you. Please let me know when you have the fix

**Pull request merged**
