### PR TITLE
KTOR-3358 Fix binary compatibility

### PR DESCRIPTION
**Pull request by e5l**
Fix [KTOR-3358](https://youtrack.jetbrains.com/issue/KTOR-3358)

### CODE REVIEW

**Comment by rsinukov** [comment]
Please check CI build, there is a compilation error

**Comment by olme04** [comment]
May be it's better to use [gradle JVM toolchains](https://blog.jetbrains.com/kotlin/2021/11/gradle-jvm-toolchain-support-in-the-kotlin-plugin/) instead of using `jdkHome` explicitly?

**Comment by e5l** [comment]
@olme04, thanks! Will check

**Comment by docee** [comment]
@e5l Hi! When will this MR be merged into the main branch?

**Review by rsinukov — APPROVED** [review]

**Review by lolilofit — APPROVED** [review]

**Review by Stexxe — APPROVED** [review]

**Comment by docee** [comment]
Hi, @e5l 
Can you release a 2.0.0 EAP version that fixes KTOR-3358?

**Pull request merged**
