### PR TITLE
Release 3.0.0-beta-1

### PR DESCRIPTION
**Pull request by Stexxe**

### CODE REVIEW

**Review by e5l — APPROVED** [review]

**Comment by pitonite** [comment]
will this beta be released on maven central ? (like the old [2.0.0-beta-1](https://mvnrepository.com/artifact/io.ktor/ktor-client-core-jvm/2.0.0-beta-1)) ?

**Comment by e5l** [comment]
Yep

**Comment by pitonite** [comment]
thanks!
how long it takes to be available ?

**Comment by e5l** [comment]
> thanks! how long it takes to be available ?

The publishing is in progress right now, we will make a GitHub release and announce it in slack :)

**Pull request merged**
