### PR TITLE
Improve KotlinxSerializer

### PR DESCRIPTION
**Pull request by sommd**
Not sure if about the name of `register()`. Might be more consistent to call it `setMapper()` as well, but that name makes less sense since there's only one parameter.

### CODE REVIEW

**Comment by e5l** [comment]
Hi, @sommd. Thanks for the PR. 
Could you add some serialization tests?

**Comment by sommd** [comment]
Refactored tests from ktor-client-gson/jackson/json/json-jvm to share a common base class (`JsonTest`). Currently the tests for `KotlinxSerializer` don't pass, since it doesn't support parameterized types. I'll look into getting it working.

**Comment by e5l** [comment]
It looks like the PR run issue with `KotlinxJsonTest.testSerializeNested` test. Could you take a look?

**Comment by sommd** [comment]
Fixed now, I made a mistake writing the test.

**Comment by e5l** [comment]
Lgtm. Thanks for the PR :)

**Pull request merged**
