### PR TITLE
KTOR-3248 Build Ktor on Apple Silicon

### PR DESCRIPTION
**Pull request by hfhbd**
**Subsystem**
Infrastructure 

**Motivation**
It is not possible to build Ktor on Apple Silicon Mac.
https://youtrack.jetbrains.com/issue/KTOR-3248

**Solution**
Adopt Gradle targets

### CODE REVIEW

**Review by e5l — APPROVED** [review]
Hey @hfhbd, thanks for the PR. LGTM
Will be merged after CI run

**Comment by hfhbd** [comment]
@e5l Just keep in mind, after coroutines 1.6.0 release you could remove this blocks:
```kotlin
// https://github.com/Kotlin/kotlinx.coroutines/issues/3001
val jna_version = "5.9.0"
api("net.java.dev.jna:jna:$jna_version")
api("net.java.dev.jna:jna-platform:$jna_version")
```

**Comment by e5l** [comment]
@hfhbd, could you check the build?

**Comment by hfhbd** [comment]
@e5l I already did. Reading only the log is not very helpful: `cinteropLibcurlMacosX64` failed with exit code 1, wow...

**Comment by e5l** [comment]
lgtm, merged

**Pull request merged**
