### PR TITLE
KTOR-6504 Fix allocation tests for 3.0.0

### PR DESCRIPTION
**Pull request by bjhham**
**Subsystem**
Server, response pipeline, static resources

**Motivation**
[KTOR-6504](https://youtrack.jetbrains.com/issue/KTOR-6504) Fix allocation tests - they're currently failing for main and all our branches due to an upward drift in allocations

**Solution**
Includes changes from @e5l's branch for improvements and one from mine, all dealing with eliminating wasteful memory allocations to get the allocation test results back down to a reasonable level.

### CODE REVIEW

**Comment by e5l** [comment]
Could you also make PR to the allocations becnhmarks repo?

**Comment by bjhham** [comment]
Oh yeah I already made one a little while ago I just haven't merged it https://github.com/ktorio/ktor-benchmarks/pull/17

I was waiting to merge the fixes first but I guess the order doesn't really matter 😄

**Pull request merged**
