### PR TITLE
Remove private modifier from Routing.interceptor

### PR DESCRIPTION
**Pull request by eld0727**
Move all inner logic of Routing to separated class to allow user use routing feature in detached mode.
Also make interceptor function public to use it independently of `install(Routing)`

Main motivation of that pull request is to allow user use dynamic routing

### CODE REVIEW

**Comment by cy6erGn0m** [comment]
Why making `interceptor` function public is not enough? What are advantages of extra inheritance and nullable application? Do you build routing with no running application? Why?

**Comment by cy6erGn0m** [comment]
Locations couldn't be registered in a routing with no application

**Comment by eld0727** [comment]
> Do you build routing with no running application? Why?

I want to do something like that:
```kotlin
val applicationRef = AtomicRef(MyApplication())
val server = embeddedServer(Netty, port = 8080) {
    intercept(ApplicationCallPipeline.Call) {
        applicationRef.get().routing.intercept(this)
    }
    routing {
        route("some static routes") {
            ...
        }
    }
}

//and in some moment reload all application components atomically
applicationRef.set(newVersionOfMyApplication)
```
> Why making interceptor function public is not enough? What are advantages of extra inheritance and nullable application?

So it allows us to create detached routing object instead of  collecting `(Routing) -> Unit`

> Locations couldn't be registered in a routing with no application

Yeah, as i can see Locations feature could not be used with detached routes at this moment.
Authentication and web sockets have the same issue. 

 @cy6erGn0m  is it a blocker for detached routes?

**Comment by cy6erGn0m** [comment]
So you actually need application reloading, like hot reload but with a custom trigger, right?

**Comment by eld0727** [comment]
Yes, i think that hot reload with no downtime could solve this issue

**Comment by eld0727** [comment]
Ok, lets just make interceptor function public

**Pull request merged**
