### PR TITLE
OverridingClassLoader now delegates to parent for resources also.

### PR DESCRIPTION
**Pull request by spand**
Previously it was (presumably) only able to find resources on its own classpath.

KTOR-4004

**Subsystem**
Server

**Motivation**
Classes were unable to load resources from the classpath when loaded in OverridingClassLoader

**Solution**
A breaking test demonstrates the problem and I have submitted a fix.

### CODE REVIEW

**Review by e5l — APPROVED** [review]
LGTM, will merge after review

**Comment by e5l** [comment]
Hey @spand, could you check the CI build?

**Comment by spand** [comment]
@e5l
Is it good now ? I think I saw another problem but all is green. Do you need to trigger a full test suite manually ?

**Comment by e5l** [comment]
Sure, in a moment

**Comment by spand** [comment]
I reworked it a bit so maybe it is fixed but I cannot reproduce the problem locally.

**Comment by spand** [comment]
@e5l I placed an ignore on the failing test. It seems pretty doomed for me to try to fix this test without access to the environment. Cant we agree that the changes are simple and makes sense enough to get this fix merged?

**Comment by e5l** [comment]
@spand, sure

**Pull request merged**
