### PR TITLE
Provide metrics with Micrometer.io -- Initial commit for discussion NOT TO MERGE!

### PR DESCRIPTION
**Pull request by dave08**
The changes don't keep the old metrics names due to the difference of how Micrometer works.

Next steps:
- How should different deps for each framework be handled?
- Should default histogram buckets be specified, or should the user be able to configure them according to their own case?
- Should any more types of metrics be introduced? As in https://vertx.io/docs/vertx-micrometer-metrics/java/ Http server section or https://github.com/nolequen/vertx-prometheus-metrics?

### CODE REVIEW

**Comment by hpoul** [comment]
Hi,
just wondering about the status of this? is micrometer the future for ktor, or just an experiment? 

thanks,
  herbert

**Comment by dave08** [comment]
@hpoul You could just copy the code and use it in your project. I started this PR since I understood there was some interest in expanding metrics support. I'm just waiting for review if this is what they expected, and then I was ready to add things like DSL for common configs, and a builder function at least for Prometheus (others could be added later...), feedback on extra metrics needed would be nice! I already have this in Production and in it's basic current form it's already very helpful!

**Comment by dave08** [comment]
@hpoul What is your use case? Will you be using some kind of Orchestration (Docker Swarm, Kubernetes, Openshift)? The truth is that whether Dropwizard will be replaced or not, your code shouldn't change too much unless you're including custom metrics in your code. And the metric names/types will be different...

**Comment by dave08** [comment]
@hpoul Then I really think you should try copying this PR over (even if it doesn't get merged, you could always use it...), since Prometheus is the most popular monitoring system for Docker, Docker Swarm and Kubernetes and Dropwizard doesn't support it. Good luck! You can even keep a reference of Micrometer before you pass it to the `Feature`. If you have any suggestions for improvements, I'd like to hear!

**Comment by orangy** [comment]
I'm not sure why do you want to replace metrics support? They could be two different features in two different modules so that user can choose which metrics library to use.

**Comment by orangy** [comment]
I would go with 
> install(DropwizardMetrics) or install(MicrometerMetrics)

for a start. I don't think a lot of people would want to install both at the same time. They should be in different modules, since they have different dependencies, obviously.

**Comment by dave08** [comment]
@orangy How could I handle the dependencies? In Micrometer, they have one for each metrics system. Like `compile 'io.micrometer:micrometer-registry-jmx:latest.release'` or `compile 'io.micrometer:micrometer-registry-prometheus:latest.release'`. Also, now there's the Dropwizard deps.

**Comment by dave08** [comment]
Ok, that seems solved. What about `AuthenticationRouteSelector` check causing a dependency on auth module? Should I add the dependency, or is there a better way of ignoring those kind of route parts?

**Comment by dave08** [comment]
So there isn't any advantage to providing both @jkschneider? Micrometer provides all the features of Dropwizard, and is even potentially backwards-compatible if the user is already using Dropwizard api in their own code?

**Comment by michael-barker** [comment]
Any updates on this?

**Comment by dave08** [comment]
I could, we are using this internally, but I'm just not sure how to split this into two modules in gradle...

**Comment by jkschneider** [comment]
@dave08 Can you describe how you are trying to divide the code into two modules in Gradle? I could probably help you with that.

**Comment by orangy** [comment]
@dave08 looks like something is wrong with the PR, lots of unrelated commits…

**Comment by dave08** [comment]
Replaced by https://github.com/ktorio/ktor/pull/718

**Pull request closed without merging**
