### PR TITLE
Build scripts: bump Gradle to 7.6

### PR DESCRIPTION
**Pull request by martinbonnin**
This fixes compiling with Java 19

### CODE REVIEW

**Comment by martinbonnin** [comment]
Never mind, I just saw this is taken care of in https://github.com/ktorio/ktor/pull/3276. Sorry for the noise.

**Comment by martinbonnin** [comment]
I changed my mind. Gradle version should be updateable independently from Kotlin and there's no need to gate Gradle 7.6 (with Java 19 support) on Kotlin updates (that sound like something more involved)

**Comment by hfhbd** [comment]
Please also update the wrapper jar. (Gradle requires calling the upgrade task twice, first updating the properties files, and the second run actually updates the wrapper file)

**Comment by martinbonnin** [comment]
Right 👍 Gradle wrapper should be updated now

**Comment by e5l** [comment]
fixed with 2.3.0

**Pull request closed without merging**
