### PR TITLE
Build scripts: Bump the toolchain version to 11

### PR DESCRIPTION
**Pull request by martinbonnin**
Looks like Adoptium did not release Java8 versions of their M1 JDKs leading to errors like below:

```
> Unable to download toolchain matching the requirements ({languageVersion=8, vendor=any, implementation=vendor-specific}) from 'https://api.adoptium.net/v3/binary/latest/8/ga/mac/aarch64/jdk/hotspot/normal/eclipse'.
  > Could not read 'https://api.adoptium.net/v3/binary/latest/8/ga/mac/aarch64/jdk/hotspot/normal/eclipse' as it does not exist.
```

Bump to Java 11 which exists. This fixes building on a M1 mac without JDK8 installed. Given this is used to compile buildSrc, it shouldn't impact the published artifacts. 

Tests fail on my `:ktor-client:ktor-client-tests:iosSimulatorArm64TestCompileKlibraries` but this fails no matter if I have a JDK8 installed or not so it seems unrelated ?

### CODE REVIEW

**Review by e5l — CHANGES_REQUESTED** [review]
We're using `8` jdk to avoid problems with `ByteBuffer` overloads with primitive types: https://stackoverflow.com/questions/61267495/exception-in-thread-main-java-lang-nosuchmethoderror-java-nio-bytebuffer-flip. 

To fix this we also need to specify -Xjdk-release

**Comment by martinbonnin** [comment]
> We're using 8 jdk to avoid problems with ByteBuffer overloads with primitive types

I agree in general but this change is for `buildSrc` so it shouldn't affect production code? And mandating Java11 for development sounds reasonnable these days?

**Comment by e5l** [comment]
It does affect the toolchain used to compile classes for release

**Comment by martinbonnin** [comment]
I'm confused. This is `buildSrc`. It generates the build logic classes, not the published ktor classes. Since it applies the `kotlin-dsl`, [it will default to 1.8](https://github.com/gradle/gradle/blob/3fed7d8caceaa13474c99e21b9cb113cac660697/subprojects/kotlin-dsl-plugins/src/main/kotlin/org/gradle/kotlin/dsl/plugins/dsl/KotlinDslPluginOptions.kt#L40).

You can double check by checking the class file version:

```
$ file buildSrc/build/classes/kotlin/main/CodestyleKt.class                                            
buildSrc/build/classes/kotlin/main/CodestyleKt.class: compiled Java class data, version 52.0 (Java 1.8)
```

Even if it were generating Java11 bytecode (which is possible with `kotlinDslPluginOptions.jvmTarget.set("11")` in `buildSrc/build.gradle.kts`), the released JVM artifacts would still generate 1.8 bytecode because [other parts of the main build change the toolchain](https://github.com/ktorio/ktor/blob/4f5954c2b9f5e5e20ea75e7e12454e4cb8c43e25/build.gradle.kts#L178). You can double check that too:

```
$ file ktor-client/ktor-client-okhttp/build/classes/kotlin/jvm/main/io/ktor/client/engine/okhttp/OkHttpEngine.class 
ktor-client/ktor-client-okhttp/build/classes/kotlin/jvm/main/io/ktor/client/engine/okhttp/OkHttpEngine.class: compiled Java class data, version 52.0 (Java 1.8)
```

Do you have a specific artifact/class in mind that should be 1.8 bytecode?

**Comment by martinbonnin** [comment]
> other parts of the main build change the toolchain

Alright, I just realized I need to change it these places too then. Not sure why I was the impression that it was working there already. I'll update this PR in a bit.

**Comment by martinbonnin** [comment]
Should be all good now, let me know what you think!

**Comment by hbmartin** [comment]
Is this what's blocking iosarm64 EAP artifacts after the Kotlin 1.8.10 upgrade?

**Pull request closed without merging**
