### PR TITLE
KTOR-1240 Fix socket timeout

### PR DESCRIPTION
**Pull request by e5l**
Fixes [KTOR-1240](https://youtrack.jetbrains.com/issue/KTOR-1240)

### CODE REVIEW

**Comment by cy6erGn0m** [comment]
mm.. the total diff adds API with no actual code change? Are you sure?

**Comment by e5l** [comment]
Fixed, please take a look

**Review by Stexxe — CHANGES_REQUESTED** [review]
Where exactly was a typo?

**Comment by e5l** [comment]
`val`->`var`

**Comment by Stexxe** [comment]
> `val`->`var`

Looks like it was done on purpose. Could you please describe in the https://youtrack.jetbrains.com/issue/KTOR-1240 why  `socketTimeout` needs to be mutable?

**Comment by e5l** [comment]
Nope, it wasn't. It's a property in config.

**Comment by e5l** [comment]
explained in the issue

**Review by Stexxe — APPROVED** [review]

**Pull request merged**
