### PR TITLE
 Add kotlinx-serialization ContentConverters for JSON, CBOR and ProtoBuf

### PR DESCRIPTION
**Pull request by sommd**

### CODE REVIEW

**Comment by PPACI** [comment]
This PR would be great !

**Comment by felipehjcosta** [comment]
I agree! @PPACI

**Comment by MrChoclate** [comment]
This is great !
I have two questions on this converters. Why register serializers and not use type.serializer() and how do you handle generic types like `call.receive<List<MyEntity>>()` ?

**Comment by cy6erGn0m** [comment]
It looks like we have `ktor-serialization` module, so we need to generalize it.

**Pull request closed without merging**
