### PR TITLE
KTOR-3733 Update slf4j to 1.7.35

### PR DESCRIPTION
**Pull request by Neustradamus**
https://www.slf4j.org/news.html

### CODE REVIEW

**Comment by Neustradamus** [comment]
@e5l, @ilmirus: It is possible to release stable build with all CVE fixes?

In the same time my PRs?
- https://github.com/ktorio/ktor/pull/2764
- https://github.com/ktorio/ktor/pull/2765

I have already done a comment here without an answer:
- https://github.com/ktorio/ktor/commit/b4eba576138372accc299ac8ae2081bb52e6706e#commitcomment-62700206

For example, there is a problem in Jitsi products:
- https://github.com/jitsi/jibri/issues/459

PS: Impossible to create an account here: https://youtrack.jetbrains.com/newIssue?project=KTOR

**Comment by Neustradamus** [comment]
Dear @ktorio team, @e5l, @ilmirus, @hhariri, @rsinukov: Happy New Year 2022!

Have you seen my PR?

Thanks in advance.

**Review by rsinukov — CHANGES_REQUESTED** [review]
Hi, 
Thanks for the PR. I see that 1.7.3 was released. Do you mind updating your PR?

**Comment by Neustradamus** [comment]
@rsinukov: I have updated the PR :)

**Review by rsinukov — APPROVED** [review]
LGTM

**Pull request merged**
