### PR TITLE
[KTOR-940] CIO TLSConfigBuilder JVM allow null as password

### PR DESCRIPTION
**Pull request by hfhbd**
**Subsystem**
CIO JVM TLSConfigBuilder

Fixing [KTOR-940](https://youtrack.jetbrains.com/issue/KTOR-940)
**Motivation**
It is legal (and possible with Apache HttpClientEngine) to use a keystore without a password. One valid and secure use-case is using a pki/smartcard middleware which is loaded as a keystore, and enforces itself the password/the smartcard pin.

**Solution**
Made password nullable

### CODE REVIEW

**Review by Stexxe — CHANGES_REQUESTED** [review]
Please add a test

**Review by e5l — CHANGES_REQUESTED** [review]
LGTM, but we really need a test for that

**Comment by hfhbd** [comment]
@e5l Unfortunately the JavaKeyStore requires a non-null password. Some other KeyStoreSpis, like the KeyStoreSpi from IT Solution GmbH/trustWare CSP+ v1.1.0.7 needs `null` as passwords, because they act as a middleware and en-/decrypt the keys with other passwords, like a PIN.
I did implement a fake KeyStoreSPI. Do you really want this?

**Comment by hfhbd** [comment]
@cy6erGn0m Currently, TLSConfigBuilder is used only by CIO Client, so Server is the wrong label :)

**Comment by hfhbd** [comment]
Switched base to master

**Review by e5l — APPROVED** [review]
Hey @hfhbd, thanks for the PR. Will be merged after CI run

**Comment by hfhbd** [comment]
@e5l After reading Binary validator, this would be a breaking change, won't it? I will create a second overload method!

**Comment by e5l** [comment]
@hfhbd that's right. Thanks for catch

**Comment by hfhbd** [comment]
@e5l added overload. Do you want a deprecation warning too?

**Comment by e5l** [comment]
Would be really great

**Comment by hfhbd** [comment]
@e5l here you go

**Comment by e5l** [comment]
It looks like there is a compilation problem:
```
e: Z:\buildAgent\work\8d547b974a7be21f\ktor-network\ktor-network-tls\jvm\test\io\ktor\network\tls\tests\TLSConfigBuilderTest.kt: (127, 63): Type mismatch: inferred type is String but Double was expected
```

Could you check?

**Comment by hfhbd** [comment]
@e5l I was wondering, why this build only fails on Java 8, but not on Java 11. I am using the new API, introduced in Java 9, which deprecated the constructor in Java 8. In Java 15, it is still available.

**Comment by hfhbd** [comment]
@e5l Could you rerun the tests?

**Comment by e5l** [comment]
Yep, sure

**Comment by e5l** [comment]
Good job! Merged

**Pull request merged**
