### PR TITLE
Add WinHTTP-based HTTP client

### PR DESCRIPTION
**Pull request by dtretyakov**
This change brings WinHTTP-based HTTP client on Windows platform. [WinHTTP library](https://docs.microsoft.com/en-us/windows/desktop/WinHttp/about-winhttp) is available since Windows XP, Windows 2000 and is used in .NET framework. 

WinHTTP provides async working mode where via request function could be trigger some operation and result of it will be returned in the [callback function](https://github.com/ktorio/ktor/blob/583d3165db23f8064b8374a1a71e9e6880f11a63/ktor-client/ktor-client-winhttp/windows/src/io/ktor/client/engine/winhttp/internal/WinHttpCallbacks.kt) which is executed on any thread from WinHTTP thread pool.

This PR addresses #671

**Note**: The latest commit (https://github.com/ktorio/ktor/commit/583d3165db23f8064b8374a1a71e9e6880f11a63) adds ability to stream request/response body by using deferred calls, but it leads to deadlocks during continuation after `.await()`, so it requires help to resolve this problem.

### CODE REVIEW

**Comment by dtretyakov** [comment]
@e5l, in the recent commit https://github.com/ktorio/ktor/pull/957/commits/17da3d2494f065d05082e43d74f97d97a88df199 was introduced synchronous working mode enabled by default where continuations are not used and as result it is not affected by deadlocks.

**Comment by e5l** [comment]
Hi @dtretyakov, thanks for the pr 
Is the implementation ready for review?

**Comment by dtretyakov** [comment]
@e5l, yes, it's ready for review and contribution. Here is the following highlights:
* The synchronous mode for WinHTTP works just fine.
* The asynchronous mode has problems with deadlocks during continuation after `await()` calls, so if you know how it could be solved please feel free to improve it. Otherwise it could be disabled for now.
* Currently request body is [loaded as `ByteArray` into memory](https://github.com/ktorio/ktor/blob/2c31d1462deab23e49446ba0b890aff0458fd42f/ktor-client/ktor-client-winhttp/windows/src/io/ktor/client/engine/winhttp/internal/WinHttpRaw.kt#L19-L27) the same way as in Curl HttpClient, but as an enhancement [it could be written as chunks](https://github.com/ktorio/ktor/blob/2c31d1462deab23e49446ba0b890aff0458fd42f/ktor-client/ktor-client-winhttp/windows/src/io/ktor/client/engine/winhttp/WinHttpClientEngine.kt#L54-L62).

**Comment by e5l** [comment]
Ok. I accept and merge the PR into `e5l/develop` to continue work on it.

**Comment by vehovsky** [comment]
Hi @e5l, any news on this one?

**Pull request merged**
