### PR TITLE
KTOR-356 fix to provide a way to configure netty pipeline with user provided custom channel handler

### PR DESCRIPTION
**Pull request by thiyagu06**
**Subsystem**
Server, ktor-server, ktor-server-netty

**Motivation**
I'm working on project where we need to add few organization cross cutting channel handler. Current implementation doesn't expose any ways to add our channel handler.
https://github.com/ktorio/ktor/issues/1909

Fix for [KTOR-356](https://youtrack.jetbrains.com/issue/KTOR-356).

**Solution**

provide a way to configure netty pipeline with user provided custom `channelHandler`.  The user provided channel handler will be added in the channel pipeline along with the default channelHandler added [here].(https://github.com/ktorio/ktor/blob/master/ktor-server/ktor-server-netty/jvm/src/io/ktor/server/netty/NettyChannelInitializer.kt#L94).

```
embeddedServer(Netty, port = configuration.server.port, configure = {
        channelPipelineConfig = {
            addAfter("codec","trafficMonitoring", TrafficMonitoringHandler())
        }
    }) {
        module()
    }.start(true)
```

### CODE REVIEW

**Comment by thiyagu06** [comment]
ping @e5l @cy6erGn0m

**Comment by e5l** [comment]
Hey, @thiyagu06. Thanks for the PR, could you run `./gradlew apiDump` and commit the API changes?

**Review by e5l — APPROVED** [review]
waiting for the API changes commit

**Comment by thiyagu06** [comment]
@e5l api dump has been added in PR. anything else needed to get this PR move forwarded?

**Comment by e5l** [comment]
Thanks, merged!

**Pull request merged**
