### PR TITLE
[WIP] KTOR-7051 Kotlin 2.0.0 upgrade

### PR DESCRIPTION
**Pull request by bjhham**
WIP, depends on kotlinx-io migration

### CODE REVIEW

**Comment by e5l** [comment]
We need to check the build, it looks like some stuff is not working

**Comment by bjhham** [comment]
Yes, I'm waiting on the kotlinx-io migration because the failing source files are removed there.

**Comment by wyaeld** [comment]
@bjhham does https://github.com/Kotlin/kotlinx-io/releases/tag/0.4.0 resolve this?

**Comment by e5l** [comment]
We need https://github.com/Kotlin/kotlinx-io/pull/334 to be merged

**Comment by e5l** [comment]
Fixed with kotlinx-io branch

**Pull request closed without merging**
