### PR TITLE
Allow other handlers beside JettyKtorHandler

### PR DESCRIPTION
**Pull request by jruuttun**
When additional jetty configuration is postponed to the startup routine, users may configure additional handlers to the chain beside the JettyKtorHandler assigned in JettyApplicationEngine.start().

This makes the embedded jetty scenario feasible while still providing support e.g. for legacy integrations from the Servlet world.

**Subsystem**
ktor-server-jetty

**Motivation**
See #1741, #270

### CODE REVIEW

**Comment by jruuttun** [comment]
bump

**Comment by jruuttun** [comment]
Closing as obsolete. See https://youtrack.jetbrains.com/issue/KTOR-436

**Comment by guai** [comment]
I think this PR still better be merged. It breaks nothing, it changes just 2 lines but adds the ability to configure jetty directly.

**Comment by jruuttun** [comment]
@guai I deleted this fork already so it probably won't happen. I suppose commenting on [KTOR-436](https://youtrack.jetbrains.com/issue/KTOR-436) would get more attention from Ktor devs.

**Comment by jruuttun** [comment]
Oops, it's not that I deleted this fork, but the `master` branch was renamed to `main` by GitHub, which prevents me from reopening...

**Pull request closed without merging**
