### PR TITLE
KTOR-7909 docs: update Linux instructions in contributing.md

### PR DESCRIPTION
**Pull request by bsautner**
**Subsystem**

Docs

**Motivation**

[KTOR-7909
](https://youtrack.jetbrains.com/issue/KTOR-7909/Update-Linux-Installation-Instructions-Replace-libncurses5-with-libncurses6-for-Ubuntu-20.04-and-Later)

As a new contributor, the instructions to build from source have an old version of libncurses and will result in a package not found error. This can be confusing to new contributors.

**Solution**

- Replace outdated 'libncurses5' packages with 'libncurses-dev' and 'libtinfo-dev' to ensure future compatibility.
- Use 'apt' instead of 'apt-get' for modern best practices.
- Simplify installation commands by combining them and removing explicit version numbers.

### CODE REVIEW

**Review by osipxd — APPROVED** [review]
LGTM! Thank you for updating this

**Comment by osipxd** [comment]
@e5l, could you merge this PR ignoring required checks?
I think we should reconfigure our CI for such cases when only markdown files are changed.

**Comment by e5l** [comment]
Hey @bsautner, thanks for the PR! LGTM

**Comment by bsautner** [comment]
Thanks @e5l , @vnikolova and @osipxd  - It was a small contribution but really meaningful to me to have a PR merged to main on this project.  I'm a distinguished engineer at Comcast and lead mobile development here, specifically with android or kmp on iOS.  Part of my role is to contribute to open source and chose to put my focus on ktor because we're using it in the xfinity android app and also I just love the project; I even have some ktor server hobby projects going.  I hope I can help more!

**Pull request merged**
