### PR TITLE
KTOR-5448 Unmute legit SerializationException

### PR DESCRIPTION
**Pull request by e5l**

### CODE REVIEW

**Comment by sandwwraith** [comment]
Don't you want to use `serializerOrNull` in `serializerFromTypeInfo`?

**Comment by e5l** [comment]
@sandwwraith, could you clarify what `serializerOrNull` we should use? We already using some `serializerOrNull` https://github.com/ktorio/ktor/blob/bad1c2da472646318a402342a249cc6300bc0940/ktor-shared/ktor-serialization/ktor-serialization-kotlinx/common/src/io/ktor/serialization/kotlinx/SerializerLookup.kt#L21 in the described case

**Comment by sandwwraith** [comment]
Ah, sorry, I didn't see that. Disregard my comment then.

**Review by marychatte — APPROVED** [review]
lgtm

**Pull request merged**
