### PR TITLE
KTOR-3174 CBOR content negotiation

### PR DESCRIPTION
**Pull request by mpetuska**
[KTOR-3174 [Ktor Client] CborFeature](https://youtrack.jetbrains.com/issue/KTOR-3174)
Superset of #2613
**Subsystem**
Client

**Motivation**
Add support for CBOR serialization format to unlock ktor client usage with CBOR servers. Also allow for easy registration of other serialization formats mapped to ContentType

**Solution**
Replicate the `serialization()` function behaviour we have for server-ContentNegotiation feature and use it to implement shortcuts for json and cbor.

To free up the name `ktor-client-serialization` for new wrapper module to encapsulate such implementations, existing json modules were renamed to follow this schema: `ktor-client-json-<<backingSerializer>>`. e.g.: `ktor-client-json-gson`, `ktor-client-json-serialization`...

**Usage**
```kotlin
install(ContentNegotiation) {
  cbor(Cbor)
}
```

### CODE REVIEW

**Comment by mpetuska** [comment]
@rsinukov ready for you again

**Comment by rsinukov** [comment]
The code looks good, but I see that compilation fails for some test tasks. Can you check it please? 
```
Compilation error: :ktor-client:ktor-client-mock:compileTestKotlinJvm
Compilation error: :ktor-client:ktor-client-tests:compileTestKotlinJvm
```

**Comment by mpetuska** [comment]
Should be all good now

**Review by rsinukov — APPROVED** [review]
Thanks for your work! LGTM

**Pull request merged**
