### PR TITLE
Upgrade kotlinx-coroutines to 1.7.1

### PR DESCRIPTION
**Pull request by bcmedeiros**
**Subsystem**
Client and Server

**Motivation**
This upgrades `kotlinx-coroutines` to 1.7, which is besides many things a blocker to https://youtrack.jetbrains.com/issue/KTOR-5753

Seems to also be a fix to https://youtrack.jetbrains.com/issue/KTOR-5728, I cannot reproduce the error anymore on my machine after this patch.

**Solution**
Upgrade library and make necessary adjustments.

### CODE REVIEW

**Comment by chris-hatton** [comment]
Lack of Coroutines 1.7.x compatibility is becoming a problem for an [increasing number](https://youtrack.jetbrains.com/issue/KTOR-5728) of KMP developers.  Hoping this can be reviewed and merged with priority.

**Comment by bcmedeiros** [comment]
Fixed some errors in CI and rebased against `main`

**Comment by bcmedeiros** [comment]
I just reverted a change suggested by the IDE earlier, that should fix the last CI errors.

Can you guys run the CI pipeline again? I think it's ready to be reviewed and merged now.

**Comment by bcmedeiros** [comment]
I hard to tell what's happening in the pipeline, I just ran the build on macOS, but could not reproduce the failure at all.

**Comment by bcmedeiros** [comment]
It seems that the last error on macOS is gone after re-running the build, the only one left is now:
> Execution failed for task ':ktor-client:ktor-client-tests:mingwX64Test'. java.lang.Error: Test running process exited unexpectedly.
>  Current test: testVaryStale

I'll see if I can setup a Windows environment so I can reproduce it, but this seems like another flaky test and probably not worth the effort.

**Comment by humblehacker** [comment]
@bcmedeiros Thanks for your work on this. Looking forward to getting this merged. You last said:

> I'll see if I can setup a Windows environment so I can reproduce it

Were you able to do this? Is this what's holding up the Ktor team's review?

**Comment by bcmedeiros** [comment]
> Were you able to do this? Is this what's holding up the Ktor team's review?

Not yet, but I don't think so, since I have seen this same error happening in other PRs (which to me means it's not being caused by any changes in this PR).

It's hard to know what's happening without any feedback from the maintainers. 🤷🏼

**Comment by bcmedeiros** [comment]
Oh, I just saw https://github.com/ktorio/ktor/pull/3621 was merged, so I'll rebase this soon and see if we get all green checks.

**Comment by bcmedeiros** [comment]
Rebased on current `main`. Not sure if the CI workflow needs to be manually approved, but let's see what happens in the next build 🤞🏼

**Review by e5l — APPROVED** [review]

**Comment by ahna92** [comment]
facing this issue as well , any alpha / beta we can use ?

**Pull request merged**
